[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
    name = "pack.ag/amqp"
    branch = "master"

[[constraint]]
    name = "github.com/Azure/azure-sdk-for-go"
    version = "15"

[[constraint]]
    name = "github.com/Azure/azure-amqp-common-go"
    version = '0.3.2'

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  branch = "master"